
ccflags-y += -I$(srctree)/$(src)/include

obj-y += fw_core.o
obj-y += find_next_bit.o
obj-y += flash_detecter.o
obj-y += fw_flash.o
obj-y += flash_emmc.o
obj-y += libfw.o
obj-y += extension.o
obj-y += message_ex.o





