

obj-y   += smc.o
obj-y   += mbus.o
obj-y   += sha1.o
obj-y   += sha.o
obj-y   += tangoxinit.o
obj-y   += tangoxutil.o
obj-y   += xenv.o
obj-y   += timer.o
obj-y   += cache.o
obj-y   += reset.o
obj-y   += lowlevel_init.o
